// Generated by CoffeeScript 1.12.1
export var increment = function(arg) {
  var commit;
  commit = arg.commit;
  return commit('INCREMENT');
};

export var decrement = function(arg) {
  var commit;
  commit = arg.commit;
  return commit('DECREMENT');
};

//# sourceMappingURL=actions.js.map
