// Generated by CoffeeScript 1.12.1
export var getCount = function(state) {
  return state.count;
};

export var getCountTwice = function(state) {
  return state.count * 2;
};

//# sourceMappingURL=getters.js.map
