// Generated by CoffeeScript 1.12.1
var mutations, state, vuex_store;

import Vue from 'vue';

import Vuex from 'vuex';

import * as actions from './actions';

import * as getters from './getters';

Vue.use(Vuex);

state = {
  count: 10
};

mutations = {
  INCREMENT: function(state) {
    return state.count += 1;
  },
  DECREMENT: function(state) {
    return state.count += 2;
  }
};

vuex_store = new Vuex.Store({
  actions: actions,
  getters: getters,
  state: state,
  mutations: mutations
});

export default vuex_store;
